import { Category, Product } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 1, name: 'Semua Menu' },
  { id: 2, name: 'Coffee' },
  { id: 3, name: 'Non-Coffee' },
  { id: 4, name: 'Pastry & Bakery' },
  { id: 5, name: 'Main Course' },
  { id: 6, name: 'Snacks' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Monochrome Black Espresso',
    description: 'Double shot espresso blend Arabica Aceh Gayo dengan notes dark chocolate dan fruity hints.',
    price: 22000,
    isAvailable: true,
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 2,
    name: 'Noir Flat White',
    description: 'Espresso kaya rasa dipadukan dengan steamed micro-foam milk yang lembut dan balance.',
    price: 28000,
    isAvailable: true,
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 3,
    name: 'Manual Brew V60 Japanese',
    description: 'Single origin bean pilihan diseduh manual dengan dripper V60 disajikan dingin segar.',
    price: 32000,
    isAvailable: true,
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 4,
    name: 'Kyoto Ceremonial Matcha Latte',
    description: 'Pure Uji Matcha autentik dari Jepang dengan susu oat pilihan dan sentuhan pemanis aren.',
    price: 35000,
    isAvailable: true,
    categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 5,
    name: 'Artisan Charcoal Latte',
    description: 'Minuman khas monokrom berbasis activated charcoal organik, vanilla beans, dan fresh milk.',
    price: 30000,
    isAvailable: true,
    categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 6,
    name: 'Classic Butter Croissant',
    description: 'Flaky, buttery French pastry renyah di luar dan lembut berlapis di dalam.',
    price: 25000,
    isAvailable: true,
    categoryId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 7,
    name: 'Dark Choco Almond Pain',
    description: 'Croissant isi pasta dark chocolate Belgia premium bertabur irisan kacang almond panggang.',
    price: 32000,
    isAvailable: true,
    categoryId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 8,
    name: 'Truffle Mushroom Toast',
    description: 'Sourdough toast artisan dengan sauteed wild mushrooms, keju parmesan, dan white truffle oil.',
    price: 48000,
    isAvailable: true,
    categoryId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 9,
    name: 'Crispy Truffle Fries',
    description: 'Kentang goreng renyah dengan aroma truffle alami dan taburan sea salt rosemary.',
    price: 28000,
    isAvailable: false,
    categoryId: 6,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
  },
];
